version: '2'
services:
  db:
    build: ./Repository
    volumes:
      - ./Repository/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  api:
    build:
      context: ./app
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./app:/go/src/github.com/user/GoDoRP/api
    ports:
      - "5000:8080"
    links:
      - db
